using ByteAI.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ByteAI.Core.Entities.Configurations;

public sealed class InterviewConfiguration : IEntityTypeConfiguration<Interview>
{
    public void Configure(EntityTypeBuilder<Interview> builder)
    {
        builder.ToTable("interviews", "interviews");
        builder.HasKey(i => i.Id);
        builder.Property(i => i.Id).HasColumnName("id").HasDefaultValueSql("gen_random_uuid()");
        builder.Property(i => i.AuthorId).HasColumnName("author_id").IsRequired();
        builder.Property(i => i.Title).HasColumnName("title").HasMaxLength(200).IsRequired();
        builder.Property(i => i.Body).HasColumnName("body").IsRequired();
        builder.Property(i => i.CodeSnippet).HasColumnName("code_snippet");
        builder.Property(i => i.Language).HasColumnName("language");
        builder.Property(i => i.Company).HasColumnName("company");
        builder.Property(i => i.Role).HasColumnName("role");
        builder.Property(i => i.Difficulty).HasColumnName("difficulty").HasDefaultValue("medium");
        builder.Property(i => i.Type).HasColumnName("type").HasDefaultValue("interview");
        builder.Property(i => i.IsActive).HasColumnName("is_active").HasDefaultValue(true);
        builder.Property(i => i.CreatedAt).HasColumnName("created_at").HasDefaultValueSql("now()");
        builder.Property(i => i.UpdatedAt).HasColumnName("updated_at").HasDefaultValueSql("now()");

        // embedding is generated by background job — map read-only, no default
        builder.Property(i => i.Embedding).HasColumnName("embedding").HasColumnType("vector(768)");

        builder.HasOne(i => i.Author).WithMany(u => u.Interviews)
            .HasForeignKey(i => i.AuthorId).OnDelete(DeleteBehavior.Cascade);

        builder.HasIndex(i => i.AuthorId).HasDatabaseName("ix_interviews_author_id");
        builder.HasIndex(i => i.CreatedAt).HasDatabaseName("ix_interviews_created_at").IsDescending();
    }
}
