-- ByteAI Seed Data (legacy monolith script — superseded by supabase/seeds/)
-- Run the modular seeds instead:
--   psql $BYTEAI_DB_URL -f supabase/seeds/seed_seniority.sql
--   psql $BYTEAI_DB_URL -f supabase/seeds/seed_domains.sql
--   psql $BYTEAI_DB_URL -f supabase/seeds/seed_badge_types.sql
--   psql $BYTEAI_DB_URL -f supabase/seeds/seed_level_types.sql
--   psql $BYTEAI_DB_URL -f supabase/seeds/seed_search_types.sql
--   psql $BYTEAI_DB_URL -f supabase/seeds/seed_tech_stacks.sql
--   psql $BYTEAI_DB_URL -f supabase/seeds/seed_users.sql
--   psql $BYTEAI_DB_URL -f supabase/seeds/seed_bytes.sql
--   psql $BYTEAI_DB_URL -f supabase/seeds/seed_byte_tech_stacks.sql
--   psql $BYTEAI_DB_URL -f supabase/seeds/seed_interviews.sql
--   psql $BYTEAI_DB_URL -f supabase/seeds/seed_interview_comments.sql
